<?php
namespace api\model;


use yii\db\ActiveRecord;

class BaseModel  extends ActiveRecord
{
    public static function getDb()
    {
        return parent::getDb(); // TODO: Change the autogenerated stub
    }
}